spring.application.name=tn-smart-bus-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/tn_smart_bus?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Monish266480@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=ReplaceThisWithAProperLongSecretKeyForProduction1234567890
app.jwt.expiration-ms=86400000
